/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validationroutines;

/**
 *
 * @author 1-NJacobs
 */
public class ValidationGUI extends javax.swing.JFrame {

    /**
     * Creates new form ValidationGUI
     */
    public ValidationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDateCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPresence = new javax.swing.JButton();
        btnPostCode = new javax.swing.JButton();
        btnEmailCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDateCheck.setText("DateCheck");
        btnDateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnDateCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, -1));

        jLabel1.setText("Validation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));

        btnPresence.setText("PresenceCheck");
        btnPresence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresenceActionPerformed(evt);
            }
        });
        getContentPane().add(btnPresence, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));

        btnPostCode.setText("PostCode");
        btnPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        btnEmailCheck.setText("EmailCheck");
        btnEmailCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmailCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateCheckActionPerformed
        // TODO add your handling code here:
        new ValidationDate().setVisible(true);
    }//GEN-LAST:event_btnDateCheckActionPerformed

    private void btnPresenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresenceActionPerformed
        // TODO add your handling code here:
        new ValidationPresence().setVisible(true);
    }//GEN-LAST:event_btnPresenceActionPerformed

    private void btnPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostCodeActionPerformed
        // TODO add your handling code here:
        new ValidationPostCode().setVisible(true);
    }//GEN-LAST:event_btnPostCodeActionPerformed

    private void btnEmailCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailCheckActionPerformed
        // TODO add your handling code here:]
        new ValidationEmail().setVisible(true);
    }//GEN-LAST:event_btnEmailCheckActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateCheck;
    private javax.swing.JButton btnEmailCheck;
    private javax.swing.JButton btnPostCode;
    private javax.swing.JButton btnPresence;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
